'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import React, { useState } from 'react';

const roboto = Inter({ subsets: ["latin"], weight: "400" });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const toggleSidebar = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  const handleMouseEnter = () => {
    setIsSidebarOpen(true);
  };

  const handleMouseLeave = () => {
    setIsSidebarOpen(false);
  };
  
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar toggleSidebar={toggleSidebar} />
        <div className="flex pt-16">
        <Sidebar isOpen={isSidebarOpen} setIsOpen={setIsSidebarOpen} />
        <div className={`flex-1 transition-all duration-300 ease-in-out ${isSidebarOpen ? 'ml-52' : 'ml-16'}`}>
            <main className="p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
